# targets:
#   $default:
#     builders:

builders:
  enum_extension:
    import: "package:enum_extension_generator/builder.dart"
    builder_factories: ["enumExtensionBuilder"]
    # The `partId` argument to `SharedPartBuilder` is "some_cool_builder"
    build_extensions: {".dart": ["extension_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    # To copy the `.g.part` content into `.g.dart` in the source tree
    applies_builders: ["source_gen|combining_builder"]